// Kelly criterion stake sizing (D-060, May 2, 2026).
//
// Five CEO design decisions (per the Kelly collaborative session):
//   1. Confidence → probability via tier-based calibration table from
//      pick_history actual win rates (NOT confidence/100, which would
//      assume the algorithm is calibrated).
//   2. Quarter Kelly (0.25 fraction) — conservative starting point.
//      Revisit after 500+ resolved bets.
//   3. Manual bankroll setting in Settings — CEO updates as desired.
//      No auto-tracking from `bets` table (avoid coupling sizing to
//      the C17 bet-tracking architecture concerns).
//   4. Per-bet cap: 5% of bankroll, hard ceiling regardless of edge.
//   5. Rounding: nearest $5.
//
// §19.3 note: future updates to PROBABILITY_BY_CONFIDENCE are
// algorithm-adjacent and should follow the manual-gate pattern (CEO
// reviews the latest pick_history hit rates and updates the constants).
// The math (Quarter Kelly, 5% cap, $5 rounding) is implementation;
// the probability table is the algorithm input.

// Calibration table — REFRESHED May 6, 2026 from synthetic backfill data.
//
// Source: 12,497 synthetic picks generated by re-scoring pre-megadeploy
// pick_history rows through the post-megadeploy algorithm (commit 03d1700,
// May 4) via the Option C backfill orchestrator (commit c82e9ed). Hit/miss
// settled via SQL JOIN against original pick_history.actual_value. Date
// range: Feb 1 → May 3, 2026.
//
// Empirical hit rates per tier (post-megadeploy algorithm × resolved
// historical outcomes, is_synthetic=true filter):
//   90+   tier:  71.8% (142 picks)
//   80-89 tier:  61.0% (210 picks)
//   70-79 tier:  57.7% (473 picks)
//   60-69 tier:  57.3% (853 picks)
//   <60   tier:  52.8% (17,099 picks — outside Kelly table, informational only)
//
// Conservative-buffer methodology: each tier's stored probability is the
// empirical hit rate MINUS a 1.5-1.8pp buffer to absorb (a) sampling noise
// at the smaller tiers (90+ has only 142 picks → ±4pp 95% CI), (b) any
// residual point-in-time bias in the synthetic backfill (forward-looking
// opp stats / pace / B2B — see /tmp/calibration_verify_may6.md for the
// empirical analysis confirming the bias is small and direction-mixed),
// and (c) margin against algorithm degradation if recent weight tuning
// shifts factor importance.
//
// Validity: synthetic calibration was empirically verified TRUSTWORTHY
// (not inflated) on May 6 via spot-check of synthetic vs original picks.
// See /tmp/calibration_verify_may6.md.
//
// Next refresh trigger:
//   - Kelly C35 milestone (May 19) for organic post-megadeploy resampling, OR
//   - Optimizer run shifts factor weights >5% on any individual factor, OR
//   - 30-day rolling hit rate diverges >3pp from these table values
//
// Treat outputs with <50 picks per tier as too noisy to update. The
// previous May 1 audit had 70-79 tier at 46.4% (sub-breakeven) — that
// reflected the BUGGY pre-megadeploy algorithm scoring, not the corrected
// post-megadeploy one. The 70-79 tier is now ABOVE break-even (57.7%);
// Kelly will recommend stakes there for the first time.
export const PROBABILITY_BY_CONFIDENCE: Record<string, number> = {
  "90+":   0.700, // empirical 71.8% (142 picks) − 1.8pp buffer
  "80-89": 0.595, // empirical 61.0% (210 picks) − 1.5pp buffer
  "70-79": 0.560, // empirical 57.7% (473 picks) − 1.7pp buffer (NOW ABOVE BREAK-EVEN)
  "60-69": 0.555, // empirical 57.3% (853 picks) − 1.8pp buffer (was 0.500 placeholder)
};

// Quarter Kelly fraction. Conservative — revisit after 500+ resolved
// bets. Standard practice in betting markets where edge estimates have
// uncertainty (which ours do given C8 + C16 unresolved).
//
// May 5: KELLY_FRACTION retained as the default constant. User can now
// override via Settings → Kelly Aggressiveness (Quarter/Half/Full).
// recommendedStake reads the live mode via readKellyFraction() if no
// explicit fraction param is passed.
export const KELLY_FRACTION = 0.25;

// Three Kelly aggressiveness modes. Quarter is conservative default,
// Half is the moderate compromise, Full is mathematically optimal but
// assumes perfect probability calibration (which our edge estimates
// don't have — C8 + C16). User selects in Settings.
export const KELLY_FRACTION_OPTIONS = {
  quarter: 0.25,
  half:    0.5,
  full:    1.0,
} as const;
export type KellyFractionMode = keyof typeof KELLY_FRACTION_OPTIONS;
export const DEFAULT_KELLY_FRACTION_MODE: KellyFractionMode = "quarter";
export const KELLY_FRACTION_KEY = "sharpai_kelly_fraction";

export function readKellyFractionMode(): KellyFractionMode {
  try {
    const stored = localStorage.getItem(KELLY_FRACTION_KEY);
    if (stored && stored in KELLY_FRACTION_OPTIONS) return stored as KellyFractionMode;
    return DEFAULT_KELLY_FRACTION_MODE;
  } catch {
    return DEFAULT_KELLY_FRACTION_MODE;
  }
}

export function writeKellyFractionMode(mode: KellyFractionMode): void {
  try {
    localStorage.setItem(KELLY_FRACTION_KEY, mode);
  } catch {
    // private mode / disabled storage — silently ignore
  }
}

// Convenience: returns the numeric multiplier (0.25/0.5/1.0) for the
// currently-selected mode.
export function readKellyFraction(): number {
  return KELLY_FRACTION_OPTIONS[readKellyFractionMode()];
}

// Per-bet hard cap as a fraction of bankroll. 5% means a $1000 bankroll
// caps any single bet at $50 regardless of how confident the algorithm
// is. Protects against single-pick blowups.
export const MAX_BET_PCT = 0.05;

// Bet size rounded to the nearest $5. Sportsbook UI typically allows
// $1 increments but $5 rounding makes the recommended stake easier to
// remember and reduces decision fatigue.
export const ROUND_TO = 5;

// localStorage key + default for the bankroll number. Manual entry in
// Settings.
export const BANKROLL_KEY = "sharpai_betting_bankroll";
export const DEFAULT_BANKROLL = 1000;

// Convert American odds to decimal payout multiplier (the "b" in the
// Kelly formula). American -110 → 0.909 (you risk 110 to win 100, net
// profit 0.909x stake). American +150 → 1.5 (you risk 100 to win 150).
export function americanToDecimal(odds: number): number {
  if (odds === 0) return 1; // safety; shouldn't happen for real props
  if (odds < 0) return 100 / Math.abs(odds);
  return odds / 100;
}

// Bucket a confidence score into the calibration table tier.
export function probabilityForConfidence(conf: number): number {
  if (conf >= 90) return PROBABILITY_BY_CONFIDENCE["90+"];
  if (conf >= 80) return PROBABILITY_BY_CONFIDENCE["80-89"];
  if (conf >= 70) return PROBABILITY_BY_CONFIDENCE["70-79"];
  return PROBABILITY_BY_CONFIDENCE["60-69"];
}

// Full Kelly fraction: f* = (b*p - q) / b
//   b = decimal payout per unit staked
//   p = win probability
//   q = 1 - p
// Returns 0 (clamped) if Kelly would suggest a negative stake — the
// pick is sub-breakeven at the given odds.
export function kellyFraction(confidence: number, odds: number): number {
  const b = americanToDecimal(odds);
  if (b <= 0) return 0;
  const p = probabilityForConfidence(confidence);
  const q = 1 - p;
  const f = (b * p - q) / b;
  return Math.max(0, f);
}

// Final recommended stake in dollars after all CEO-decision filters:
//   - Kelly fraction (default: Quarter Kelly via readKellyFraction;
//     can be overridden by passing `fraction` explicitly)
//   - 5% of bankroll cap
//   - Round to nearest $5
// Returns 0 when full Kelly is non-positive (sub-breakeven tier).
//
// May 5: `fraction` param added. If omitted, reads from localStorage
// (Settings → Kelly Aggressiveness). All existing call sites pass no
// fraction → continue working with whatever the user has selected.
export function recommendedStake(params: {
  confidence: number; odds: number; bankroll: number; fraction?: number;
}): number {
  const fullKelly = kellyFraction(params.confidence, params.odds);
  if (fullKelly <= 0) return 0;
  if (params.bankroll <= 0) return 0;

  const frac = params.fraction ?? readKellyFraction();
  const kellyStake = fullKelly * frac * params.bankroll;
  const capStake = MAX_BET_PCT * params.bankroll;
  const cappedStake = Math.min(kellyStake, capStake);

  return Math.round(cappedStake / ROUND_TO) * ROUND_TO;
}

// Detailed breakdown for the inline tooltip on Dashboard. Returns every
// derivable field so the UI doesn't redo the math.
export interface KellyBreakdown {
  probability: number;          // calibrated win prob from confidence tier (0-1)
  decimalOdds: number;          // b in Kelly formula (americanToDecimal)
  breakEvenProb: number;        // implied break-even from odds (1 / (b + 1))
  edgePct: number;              // (probability - breakEvenProb) * 100
  fullKellyPct: number;         // f* in pct of bankroll
  fractionMode: KellyFractionMode;
  fractionMultiplier: number;   // 0.25/0.5/1.0
  rawStakePct: number;          // fullKellyPct * fractionMultiplier
  preCappedStake: number;       // raw $ before 5% cap
  capStake: number;             // 5% bankroll in $
  capApplied: boolean;          // did 5% cap kick in?
  finalStake: number;           // rounded final $ stake
  bankroll: number;
}

export function kellyBreakdown(params: {
  confidence: number; odds: number; bankroll: number; fraction?: number;
}): KellyBreakdown {
  const p = probabilityForConfidence(params.confidence);
  const b = americanToDecimal(params.odds);
  const breakEvenProb = b > 0 ? 1 / (b + 1) : 1;
  const edgePct = (p - breakEvenProb) * 100;
  const f = kellyFraction(params.confidence, params.odds);
  const fullKellyPct = f * 100;

  // Resolve fractionMode from explicit fraction param if passed; else read live.
  let mode: KellyFractionMode;
  let frac: number;
  if (params.fraction != null) {
    frac = params.fraction;
    const matched = (Object.entries(KELLY_FRACTION_OPTIONS) as [KellyFractionMode, number][])
      .find(([, v]) => Math.abs(v - frac) < 0.01);
    mode = matched ? matched[0] : DEFAULT_KELLY_FRACTION_MODE;
  } else {
    mode = readKellyFractionMode();
    frac = KELLY_FRACTION_OPTIONS[mode];
  }

  const rawStakePct = fullKellyPct * frac;
  const preCappedStake = (rawStakePct / 100) * params.bankroll;
  const capStake = MAX_BET_PCT * params.bankroll;
  const cappedStake = Math.min(preCappedStake, capStake);
  const capApplied = preCappedStake > capStake;
  const finalStake = preCappedStake > 0 ? Math.round(cappedStake / ROUND_TO) * ROUND_TO : 0;

  return {
    probability: p,
    decimalOdds: b,
    breakEvenProb,
    edgePct,
    fullKellyPct,
    fractionMode: mode,
    fractionMultiplier: frac,
    rawStakePct,
    preCappedStake,
    capStake,
    capApplied,
    finalStake,
    bankroll: params.bankroll,
  };
}

// Bankroll persistence helpers. localStorage-backed; manual CEO entry
// in Settings. No auto-derivation from `bets` table — see C17 in
// framework §15.1 for why bet-tracking is decoupled from sizing.
export function readBankroll(): number {
  try {
    const stored = localStorage.getItem(BANKROLL_KEY);
    if (!stored) return DEFAULT_BANKROLL;
    const n = parseFloat(stored);
    return Number.isFinite(n) && n > 0 ? n : DEFAULT_BANKROLL;
  } catch {
    return DEFAULT_BANKROLL;
  }
}

export function writeBankroll(amount: number): void {
  try {
    localStorage.setItem(BANKROLL_KEY, String(amount));
  } catch {
    // private mode / disabled storage — silently ignore
  }
}
