// _shared/mlb_weights.ts — D-340 / T6.
//
// Mirrors NBA's loadWeightsFromDB pattern at _shared/scoring.ts:309.
// Reads algorithm_weights row 1, maps w_mlb_* columns to MlbScoringWeights
// structure (W / W_BATTER / W_GAME sub-objects matching scoring_mlb_v2.ts).
//
// On any failure (no env, fetch error, missing row), returns defaults so
// scoring code falls back to pre-D-340 hardcoded values. Defense in depth.
//
// Usage in process-games-mlb:
//   import { loadMlbWeightsFromDB } from "../_shared/mlb_weights.ts";
//   import { setMlbWeights } from "../_shared/scoring_mlb_v2.ts";
//   const weights = await loadMlbWeightsFromDB();
//   setMlbWeights(weights);
//   // ... scoring runs with DB-loaded values ...

import { getMlbDefaultWeights, type MlbScoringWeights } from "./scoring_mlb_v2.ts";

// D-534 — known MLB market types (mirrors ALLOWED_MLB_MARKET_TYPES in
// pick_history_writer.ts). The loader pre-materializes a perMarket map
// keyed on these so the dispatcher's setActiveMarket(market) lookup is
// O(1) and so callers don't have to know which markets exist.
const KNOWN_MLB_MARKETS: readonly string[] = [
  "pitcher_k", "batter_hits", "batter_hr", "batter_total_bases",
  "batter_rbis", "game_side", "game_total",
  "batter_strikeouts", "batter_runs_scored", "pitcher_outs",
] as const;

// Mapping from the in-DB column name → the typed object path in
// MlbScoringWeights. The override JSONB's keys are DB column names
// (so overrides can be written by humans reading the schema), but
// we need to apply them to the structured W/W_BATTER/W_GAME objects.
//
// Generated by scanning the existing num(...) calls below (one entry
// per `w.<column>` reference). Each entry is:
//   "<db_column>": { group: "W"|"W_BATTER"|"W_GAME", key: "<typed_field>" }
const COL_TO_PATH: Record<string, { group: "W" | "W_BATTER" | "W_GAME"; key: string }> = {
  // W (pitcher)
  w_mlb_pitcher_k_rate:           { group: "W", key: "pitcherKRate" },
  w_mlb_pitcher_form:             { group: "W", key: "pitcherForm" },
  w_mlb_opposing_lineup_k:        { group: "W", key: "opposingLineupK" },
  w_mlb_handedness_matchup:       { group: "W", key: "handednessMatchup" },
  w_mlb_pitch_count_trend:        { group: "W", key: "pitchCountTrend" },
  w_mlb_rest_pitcher:             { group: "W", key: "restPitcher" },
  w_mlb_pitcher_ballpark_factor:  { group: "W", key: "ballparkFactor" },
  w_mlb_pitcher_weather_wind:     { group: "W", key: "weatherWind" },
  w_mlb_pitcher_weather_temp:     { group: "W", key: "weatherTemp" },
  w_mlb_pitcher_umpire_k_zone:    { group: "W", key: "umpireKZone" },
  w_mlb_pitcher_command_trend:    { group: "W", key: "pitcherCommandTrend" },
  w_mlb_pitcher_velocity_trend:   { group: "W", key: "pitcherVelocityTrend" },
  w_mlb_lineup_k_composition:     { group: "W", key: "lineupKComposition" },
  w_mlb_pitcher_xera_edge:        { group: "W", key: "pitcherXeraEdge" },
  w_mlb_pitcher_baa:              { group: "W", key: "pitcherBaa" },
  w_mlb_catcher_framing:          { group: "W", key: "catcherFraming" },
  w_mlb_pitcher_pitch_mix_k:      { group: "W", key: "pitcherPitchMixK" },
  // W_BATTER
  w_mlb_batter_hit_rate:               { group: "W_BATTER", key: "hitRate" },
  w_mlb_batter_form:                   { group: "W_BATTER", key: "form" },
  w_mlb_batter_pitcher_quality:        { group: "W_BATTER", key: "pitcherQuality" },
  w_mlb_batter_recent_ab:              { group: "W_BATTER", key: "recentAB" },
  w_mlb_batter_handedness_matchup:     { group: "W_BATTER", key: "handednessMatchup" },
  w_mlb_batter_ballpark_hits_factor:   { group: "W_BATTER", key: "ballparkHitsFactor" },
  w_mlb_batter_weather_temp:           { group: "W_BATTER", key: "weatherTemp" },
  w_mlb_batter_lineup_consistency:     { group: "W_BATTER", key: "lineupConsistency" },
  w_mlb_batter_power_rate:             { group: "W_BATTER", key: "powerRate" },
  w_mlb_batter_form_power:             { group: "W_BATTER", key: "formPower" },
  w_mlb_batter_pitcher_hr_rate:        { group: "W_BATTER", key: "pitcherHrRate" },
  w_mlb_batter_weather_wind:           { group: "W_BATTER", key: "weatherWind" },
  w_mlb_lineup_spot:                   { group: "W_BATTER", key: "lineupSpot" },
  w_mlb_day_after_night_fatigue:       { group: "W_BATTER", key: "dayAfterNightFatigue" },
  w_mlb_travel_getaway:                { group: "W_BATTER", key: "travelGetaway" },
  w_mlb_pitcher_baa_vs_hand:           { group: "W_BATTER", key: "opposingPitcherBaaVsHand" },
  w_mlb_hitter_streak_fatigue:         { group: "W_BATTER", key: "hitterStreakFatigue" },
  w_mlb_batter_xba:                    { group: "W_BATTER", key: "xba" },
  w_mlb_batter_exit_velo_trend:        { group: "W_BATTER", key: "exitVeloTrend" },
  w_mlb_batter_barrel_rate:            { group: "W_BATTER", key: "barrelRate" },
  w_mlb_batter_xslg_regression:        { group: "W_BATTER", key: "xslgRegression" },
  w_mlb_batter_babip:                  { group: "W_BATTER", key: "babip" },
  w_mlb_batter_vs_pitcher_hand_split:  { group: "W_BATTER", key: "vsPitcherHandSplit" },
  w_mlb_bullpen_quality:               { group: "W_BATTER", key: "bullpenQuality" },
  w_mlb_wind_direction_hr:             { group: "W_BATTER", key: "windDirectionHr" },
  w_mlb_pitcher_hr_per_9:              { group: "W_BATTER", key: "pitcherHrPer9" },
  w_mlb_batter_line_hit_rate:          { group: "W_BATTER", key: "lineHitRate" },
  // D-797 — 4 new extra-base factors (TB primary). Defaults in DEFAULT_W_BATTER:
  // xwoba 1.5 (research-validated primary), launchAngle/sweetSpot/hardHit 1.0.
  w_mlb_batter_xwoba:                  { group: "W_BATTER", key: "xwoba" },
  w_mlb_batter_launch_angle:           { group: "W_BATTER", key: "launchAngle" },
  w_mlb_batter_sweet_spot:             { group: "W_BATTER", key: "sweetSpot" },
  w_mlb_batter_hard_hit:               { group: "W_BATTER", key: "hardHit" },
  // D-803 — pitcher hard-contact-allowed (matchup counterpart). Default 1.0.
  w_mlb_pitcher_hard_contact_allowed:  { group: "W_BATTER", key: "pitcherHardContactAllowed" },
  // D-807 — lineup protection + team offense (runs-only high-value).
  w_mlb_batter_lineup_protection:      { group: "W_BATTER", key: "lineupProtection" },
  w_mlb_batter_team_offense:           { group: "W_BATTER", key: "teamOffense" },
  // D-808 — sprint speed (baserunning, runs-only).
  w_mlb_batter_sprint_speed:           { group: "W_BATTER", key: "sprintSpeed" },
  // D-816 — pull rate (HR-only). The missing HR-specific factor per D-811.
  w_mlb_batter_pull_rate:              { group: "W_BATTER", key: "pullRate" },
  // D-817 — pull × pull-side fence (HR-only). Directional park amplifier on D-816.
  w_mlb_batter_pull_x_park_fence:      { group: "W_BATTER", key: "pullXParkFence" },
  // D-824 — batter contact-rate / whiff-rate (hits-only discriminator).
  w_mlb_batter_contact_rate:           { group: "W_BATTER", key: "contactRate" },
  // W_GAME
  w_mlb_game_offense_diff:        { group: "W_GAME", key: "offenseDiff" },
  w_mlb_game_pitching_matchup:    { group: "W_GAME", key: "pitchingMatchup" },
  w_mlb_game_bullpen_strength:    { group: "W_GAME", key: "bullpenStrength" },
  w_mlb_game_recent_run_diff:     { group: "W_GAME", key: "recentRunDiff" },
  w_mlb_game_h2h_recent:          { group: "W_GAME", key: "h2hRecent" },
  w_mlb_game_team_form:           { group: "W_GAME", key: "teamForm" },
  w_mlb_game_ballpark:            { group: "W_GAME", key: "ballpark" },
  w_mlb_game_weather_wind:        { group: "W_GAME", key: "weatherWind" },
  w_mlb_game_weather_temp:        { group: "W_GAME", key: "weatherTemp" },
  w_mlb_game_umpire_k_zone:       { group: "W_GAME", key: "umpireKZone" },
  w_mlb_lineup_vs_hand_split:     { group: "W_GAME", key: "lineupVsHand" },
  // D-614 — D-598's batter-side pitch-type matchup factor weight. Missing
  // here previously → loadMlbWeightsFromDB returned a W_BATTER without
  // the key → `W_BATTER.oppPitcherPitchTypeQuality === undefined` → every
  // `Math.round(f * undefined) = NaN` → confidence NaN → D-529 validator
  // rejected the pick. ~3,963 batter picks/24h were lost to this.
  w_mlb_batter_opp_pitcher_pitchtype_quality: { group: "W_BATTER", key: "oppPitcherPitchTypeQuality" },
};

/** Apply per-market overrides on top of the global weight set.
 *  Pure function — no I/O. Exported for unit testing. */
export function applyOverrides(
  global: MlbScoringWeights,
  overrides: Record<string, Record<string, number>>,
): Record<string, MlbScoringWeights> {
  const out: Record<string, MlbScoringWeights> = {};
  for (const market of KNOWN_MLB_MARKETS) {
    const marketOverride = overrides[market] ?? {};
    const w: MlbScoringWeights = {
      W: { ...global.W },
      W_BATTER: { ...global.W_BATTER },
      W_GAME: { ...global.W_GAME },
    };
    for (const [colName, value] of Object.entries(marketOverride)) {
      const path = COL_TO_PATH[colName];
      if (!path) continue; // unknown column — silently skip (forward-compat)
      if (typeof value !== "number" || !Number.isFinite(value)) continue;
      const group = w[path.group] as Record<string, number>;
      group[path.key] = value;
    }
    out[market] = w;
  }
  return out;
}

/** Loads the global weights AND the per-market overrides map in one
 *  round-trip. Returns:
 *    - global: the existing W/W_BATTER/W_GAME structure (backward-compat)
 *    - perMarket: Record<market, MlbScoringWeights> with overrides applied
 *  When the JSONB column is empty (the default), every perMarket entry
 *  is byte-identical to global. */
export async function loadMlbWeightsWithPerMarket(): Promise<{
  global: MlbScoringWeights;
  perMarket: Record<string, MlbScoringWeights>;
}> {
  const global = await loadMlbWeightsFromDB();
  // Pull the overrides JSONB column. On any error → empty overrides
  // → perMarket entries === global → byte-identical scoring.
  let overrides: Record<string, Record<string, number>> = {};
  try {
    const url = Deno.env.get("SUPABASE_URL");
    const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (url && key) {
      const res = await fetch(
        `${url}/rest/v1/algorithm_weights?id=eq.1&select=mlb_market_weight_overrides`,
        { headers: { apikey: key, Authorization: `Bearer ${key}` } },
      );
      if (res.ok) {
        const rows = (await res.json()) as Array<{ mlb_market_weight_overrides?: unknown }>;
        const raw = rows[0]?.mlb_market_weight_overrides;
        if (raw && typeof raw === "object") {
          overrides = raw as Record<string, Record<string, number>>;
        }
      }
    }
  } catch (e) {
    console.log(`[mlb_weights] D-534 overrides load failed (using empty): ${e}`);
  }
  const perMarket = applyOverrides(global, overrides);
  const overrideKeys = Object.keys(overrides);
  console.log(
    `[mlb_weights] D-534 per-market loaded: ${overrideKeys.length} markets with overrides ` +
      `(${overrideKeys.join(",") || "none — all byte-identical to global"})`,
  );
  return { global, perMarket };
}

export async function loadMlbWeightsFromDB(): Promise<MlbScoringWeights> {
  const fallback = getMlbDefaultWeights();
  try {
    const url = Deno.env.get("SUPABASE_URL");
    const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if (!url || !key) {
      console.log("[mlb_weights] No DB credentials, using TS defaults");
      return fallback;
    }
    const res = await fetch(`${url}/rest/v1/algorithm_weights?id=eq.1&select=*`, {
      headers: { apikey: key, Authorization: `Bearer ${key}` },
    });
    if (!res.ok) {
      console.log(`[mlb_weights] DB fetch failed: ${res.status}, using defaults`);
      return fallback;
    }
    const rows = await res.json() as Array<Record<string, unknown>>;
    if (rows.length === 0) {
      console.log("[mlb_weights] No weights row found, using defaults");
      return fallback;
    }
    const w = rows[0];
    const num = (v: unknown, fb: number): number => {
      const n = typeof v === "number" ? v : Number(v);
      return Number.isFinite(n) ? n : fb;
    };
    const loaded: MlbScoringWeights = {
      W: {
        pitcherKRate:      num(w.w_mlb_pitcher_k_rate,         fallback.W.pitcherKRate),
        pitcherForm:       num(w.w_mlb_pitcher_form,           fallback.W.pitcherForm),
        opposingLineupK:   num(w.w_mlb_opposing_lineup_k,      fallback.W.opposingLineupK),
        handednessMatchup: num(w.w_mlb_handedness_matchup,     fallback.W.handednessMatchup),
        pitchCountTrend:   num(w.w_mlb_pitch_count_trend,      fallback.W.pitchCountTrend),
        restPitcher:       num(w.w_mlb_rest_pitcher,           fallback.W.restPitcher),
        ballparkFactor:    num(w.w_mlb_pitcher_ballpark_factor, fallback.W.ballparkFactor),
        weatherWind:       num(w.w_mlb_pitcher_weather_wind,   fallback.W.weatherWind),
        weatherTemp:       num(w.w_mlb_pitcher_weather_temp,   fallback.W.weatherTemp),
        umpireKZone:       num(w.w_mlb_pitcher_umpire_k_zone,  fallback.W.umpireKZone),
        // D-348
        pitcherCommandTrend: num(w.w_mlb_pitcher_command_trend, fallback.W.pitcherCommandTrend),
        // D-349
        pitcherVelocityTrend: num(w.w_mlb_pitcher_velocity_trend, fallback.W.pitcherVelocityTrend),
        // D-354
        lineupKComposition: num(w.w_mlb_lineup_k_composition, fallback.W.lineupKComposition),
        // D-362 — finish DB-tunable wiring for the 4 pitcher-side factors
        // that D-340 missed (literal `* 1.0` sites at scoring_mlb_v2.ts:578,
        // 592, 618, 641). Defaults match the previous hardcoded literal.
        pitcherXeraEdge:   num(w.w_mlb_pitcher_xera_edge,   fallback.W.pitcherXeraEdge),
        pitcherBaa:        num(w.w_mlb_pitcher_baa,         fallback.W.pitcherBaa),
        catcherFraming:    num(w.w_mlb_catcher_framing,     fallback.W.catcherFraming),
        pitcherPitchMixK:  num(w.w_mlb_pitcher_pitch_mix_k, fallback.W.pitcherPitchMixK),
        // D-752 fix — D-749 added score_pitcher_csw factor + DEFAULT_W.pitcherCsw=1.0
        // but missed wiring the loader. setMlbWeights does `W = { ...weights.W }`
        // (REPLACE not merge), so a loader-missing key becomes undefined at runtime.
        // That produced f_csw * undefined = NaN, cascading through factor_sum → λ
        // → win_prob → raw_conf → applyD743IsotonicCalibrationPitcherK falling
        // through every `if (x <= N)` branch to return 71 unconditionally.
        // The weight VALUE here is unchanged (default 1.0 per D-749 seed) — pure
        // wiring repair.
        pitcherCsw:        num(w.w_mlb_pitcher_csw,         fallback.W.pitcherCsw),
        // D-753 — pitchTypeMatchup (D-596) was the only other DEFAULT_W key
        // missing from the loader pre-D-753 sweep. The factor body at
        // scoring_mlb_v2.ts:904 defensively uses `W.pitchTypeMatchup ?? 1.0`,
        // so the missing loader didn't manifest as a NaN cascade (unlike
        // D-749's pitcherCsw which had no defensive fallback). Wiring it
        // closes the latent risk: a future contributor copying the pattern
        // without the `?? 1.0` would hit the same class of bug. Value
        // unchanged from D-749's DEFAULT_W seed (1.0) — pure wiring.
        pitchTypeMatchup:  num(w.w_mlb_pitch_type_matchup, fallback.W.pitchTypeMatchup),
        // D-760 — pitcher_outs weights moved from literals to DB-tunable (per
        // D-759 audit). 17 keys seeded at the EXACT literal values that were
        // hardcoded in scorePitcherOuts. No value change vs in-prod scoring.
        outsPitcherAvgIp:            num(w.w_mlb_outs_pitcher_avg_ip,             fallback.W.outsPitcherAvgIp),
        outsPitcherRecentIpTrend:    num(w.w_mlb_outs_pitcher_recent_ip_trend,    fallback.W.outsPitcherRecentIpTrend),
        outsPitcherVolatilityV2:     num(w.w_mlb_outs_pitcher_volatility_v2,      fallback.W.outsPitcherVolatilityV2),
        outsRestPitcher:             num(w.w_mlb_outs_rest_pitcher,               fallback.W.outsRestPitcher),
        outsPitcherWalkEfficiency:   num(w.w_mlb_outs_pitcher_walk_efficiency,    fallback.W.outsPitcherWalkEfficiency),
        outsPitcherRecentPitchCount: num(w.w_mlb_outs_pitcher_recent_pitch_count, fallback.W.outsPitcherRecentPitchCount),
        outsFirstInningTrouble:      num(w.w_mlb_outs_first_inning_trouble,       fallback.W.outsFirstInningTrouble),
        outsBullpenGameOrOpener:     num(w.w_mlb_outs_bullpen_game_or_opener,     fallback.W.outsBullpenGameOrOpener),
        outsOwnPenRest:              num(w.w_mlb_outs_own_pen_rest,               fallback.W.outsOwnPenRest),
        outsGameScriptRisk:          num(w.w_mlb_outs_game_script_risk,           fallback.W.outsGameScriptRisk),
        outsOppKRate:                num(w.w_mlb_outs_opp_k_rate,                 fallback.W.outsOppKRate),
        outsOppObpPatience:          num(w.w_mlb_outs_opp_obp_patience,           fallback.W.outsOppObpPatience),
        outsOppWalkRate:             num(w.w_mlb_outs_opp_walk_rate,              fallback.W.outsOppWalkRate),
        outsOppPitchGrind:           num(w.w_mlb_outs_opp_pitch_grind,            fallback.W.outsOppPitchGrind),
        outsOppChaseRate:            num(w.w_mlb_outs_opp_chase_rate,             fallback.W.outsOppChaseRate),
        outsBallparkFactor:          num(w.w_mlb_outs_ballpark_factor,            fallback.W.outsBallparkFactor),
        outsWeatherTemp:             num(w.w_mlb_outs_weather_temp,               fallback.W.outsWeatherTemp),
        // D-761 — 2 new pitcher_outs factors targeting D-760's under-side gap.
        outsThirdTimeThrough:        num(w.w_mlb_outs_third_time_through,         fallback.W.outsThirdTimeThrough),
        outsPitchesPerIp:            num(w.w_mlb_outs_pitches_per_ip,             fallback.W.outsPitchesPerIp),
        // D-763 — REAL manager-hook factor (closes D-668-FOLLOWUP-PULL-FEED).
        outsManagerHook:             num(w.w_mlb_outs_manager_hook,               fallback.W.outsManagerHook),
      },
      W_BATTER: {
        hitRate:            num(w.w_mlb_batter_hit_rate,             fallback.W_BATTER.hitRate),
        form:               num(w.w_mlb_batter_form,                 fallback.W_BATTER.form),
        pitcherQuality:     num(w.w_mlb_batter_pitcher_quality,      fallback.W_BATTER.pitcherQuality),
        recentAB:           num(w.w_mlb_batter_recent_ab,            fallback.W_BATTER.recentAB),
        handednessMatchup:  num(w.w_mlb_batter_handedness_matchup,   fallback.W_BATTER.handednessMatchup),
        ballparkHitsFactor: num(w.w_mlb_batter_ballpark_hits_factor, fallback.W_BATTER.ballparkHitsFactor),
        weatherTemp:        num(w.w_mlb_batter_weather_temp,         fallback.W_BATTER.weatherTemp),
        lineupConsistency:  num(w.w_mlb_batter_lineup_consistency,   fallback.W_BATTER.lineupConsistency),
        powerRate:          num(w.w_mlb_batter_power_rate,           fallback.W_BATTER.powerRate),
        formPower:          num(w.w_mlb_batter_form_power,           fallback.W_BATTER.formPower),
        pitcherHrRate:      num(w.w_mlb_batter_pitcher_hr_rate,      fallback.W_BATTER.pitcherHrRate),
        weatherWind:        num(w.w_mlb_batter_weather_wind,         fallback.W_BATTER.weatherWind),
        // D-347 — 3 new batter factors
        lineupSpot:            num(w.w_mlb_lineup_spot,                 fallback.W_BATTER.lineupSpot),
        dayAfterNightFatigue:  num(w.w_mlb_day_after_night_fatigue,     fallback.W_BATTER.dayAfterNightFatigue),
        travelGetaway:         num(w.w_mlb_travel_getaway,              fallback.W_BATTER.travelGetaway),
        // D-349
        opposingPitcherBaaVsHand: num(w.w_mlb_pitcher_baa_vs_hand,      fallback.W_BATTER.opposingPitcherBaaVsHand),
        // D-354
        hitterStreakFatigue:      num(w.w_mlb_hitter_streak_fatigue,    fallback.W_BATTER.hitterStreakFatigue),
        // D-362 — finish DB-tunable wiring for the 9 batter-side factors
        // that D-340 missed (literal `* 1.0` sites at scoring_mlb_v2.ts:1344,
        // 1356, 1369, 1380, 1384, 1437, 1460, 1503, 1518). Defaults match
        // the previous hardcoded literal (all 1.0).
        xba:                   num(w.w_mlb_batter_xba,                       fallback.W_BATTER.xba),
        exitVeloTrend:         num(w.w_mlb_batter_exit_velo_trend,           fallback.W_BATTER.exitVeloTrend),
        barrelRate:            num(w.w_mlb_batter_barrel_rate,               fallback.W_BATTER.barrelRate),
        xslgRegression:        num(w.w_mlb_batter_xslg_regression,           fallback.W_BATTER.xslgRegression),
        babip:                 num(w.w_mlb_batter_babip,                     fallback.W_BATTER.babip),
        vsPitcherHandSplit:    num(w.w_mlb_batter_vs_pitcher_hand_split,     fallback.W_BATTER.vsPitcherHandSplit),
        bullpenQuality:        num(w.w_mlb_bullpen_quality,                  fallback.W_BATTER.bullpenQuality),
        windDirectionHr:       num(w.w_mlb_wind_direction_hr,                fallback.W_BATTER.windDirectionHr),
        pitcherHrPer9:         num(w.w_mlb_pitcher_hr_per_9,                 fallback.W_BATTER.pitcherHrPer9),
        // D-520-APPLY — D-517 v2 line-hit-rate penalty factor
        lineHitRate:           num(w.w_mlb_batter_line_hit_rate,             fallback.W_BATTER.lineHitRate),
        // D-614 — D-598's batter-side pitch-type matchup factor weight.
        // PRE-D-614 this key was missing from the returned W_BATTER object,
        // causing W_BATTER.oppPitcherPitchTypeQuality === undefined and
        // confidence-NaN rejection of every batter pick. Default 1.0.
        oppPitcherPitchTypeQuality: num(w.w_mlb_batter_opp_pitcher_pitchtype_quality, fallback.W_BATTER.oppPitcherPitchTypeQuality),
        // D-797 — 4 new extra-base factors (close D-796 gap).
        xwoba:                 num(w.w_mlb_batter_xwoba,                     fallback.W_BATTER.xwoba),
        launchAngle:           num(w.w_mlb_batter_launch_angle,              fallback.W_BATTER.launchAngle),
        sweetSpot:             num(w.w_mlb_batter_sweet_spot,                fallback.W_BATTER.sweetSpot),
        hardHit:               num(w.w_mlb_batter_hard_hit,                  fallback.W_BATTER.hardHit),
        // D-803 — pitcher hard-contact-allowed (close D-800 gap on pitcher side).
        pitcherHardContactAllowed: num(w.w_mlb_pitcher_hard_contact_allowed, fallback.W_BATTER.pitcherHardContactAllowed),
        // D-807 — lineup protection + team offense (runs-only high-value).
        lineupProtection:      num(w.w_mlb_batter_lineup_protection,        fallback.W_BATTER.lineupProtection),
        teamOffense:           num(w.w_mlb_batter_team_offense,             fallback.W_BATTER.teamOffense),
        // D-808 — sprint speed (baserunning, runs-only).
        sprintSpeed:           num(w.w_mlb_batter_sprint_speed,             fallback.W_BATTER.sprintSpeed),
        // D-816 — pull rate (HR-only).
        pullRate:              num(w.w_mlb_batter_pull_rate,                fallback.W_BATTER.pullRate),
        // D-817 — pull × pull-side fence (HR-only).
        pullXParkFence:        num(w.w_mlb_batter_pull_x_park_fence,        fallback.W_BATTER.pullXParkFence),
        // D-824 — contact-rate / whiff-rate (hits-only).
        contactRate:           num(w.w_mlb_batter_contact_rate,             fallback.W_BATTER.contactRate),
      },
      W_GAME: {
        offenseDiff:     num(w.w_mlb_game_offense_diff,        fallback.W_GAME.offenseDiff),
        pitchingMatchup: num(w.w_mlb_game_pitching_matchup,    fallback.W_GAME.pitchingMatchup),
        bullpenStrength: num(w.w_mlb_game_bullpen_strength,    fallback.W_GAME.bullpenStrength),
        recentRunDiff:   num(w.w_mlb_game_recent_run_diff,     fallback.W_GAME.recentRunDiff),
        h2hRecent:       num(w.w_mlb_game_h2h_recent,          fallback.W_GAME.h2hRecent),
        teamForm:        num(w.w_mlb_game_team_form,           fallback.W_GAME.teamForm),
        ballpark:        num(w.w_mlb_game_ballpark,            fallback.W_GAME.ballpark),
        weatherWind:     num(w.w_mlb_game_weather_wind,        fallback.W_GAME.weatherWind),
        weatherTemp:     num(w.w_mlb_game_weather_temp,        fallback.W_GAME.weatherTemp),
        umpireKZone:     num(w.w_mlb_game_umpire_k_zone,       fallback.W_GAME.umpireKZone),
        lineupVsHand:    num(w.w_mlb_lineup_vs_hand_split,     fallback.W_GAME.lineupVsHand),
      },
    };
    console.log(
      `[mlb_weights] Loaded from DB: pitcherKRate=${loaded.W.pitcherKRate} ` +
        `batterHitRate=${loaded.W_BATTER.hitRate} gameOffenseDiff=${loaded.W_GAME.offenseDiff}`,
    );
    return loaded;
  } catch (err) {
    console.log(`[mlb_weights] Load error: ${err} — using defaults`);
    return fallback;
  }
}
